name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  test_and_lint:
    runs-on: self-hosted
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
      SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python and uv
      uses: astral-sh/setup-uv@v1
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        uv venv
        echo ".venv/bin" >> $GITHUB_PATH
        uv pip install -r requirements.txt
        uv pip install pytest ruff

    - name: Check formatting
      run: ruff format --check .

    - name: Lint
      run: ruff check .

    - name: Type check
      run: mypy .
      continue-on-error: true

    - name: Test
      run: pytest

  build_and_push:
    needs: test_and_lint
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/maokami/paperwhale:latest

  deploy:
    needs: build_and_push
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.K3S_KUBECONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Create DB Secret
      run: |
        cat <<EOF > db-secret.yaml
        apiVersion: v1
        kind: Secret
        metadata:
          name: db-secret
        type: Opaque
        stringData:
          DATABASE_URL: "${{ secrets.DATABASE_URL }}"
        EOF

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f db-secret.yaml
        kubectl apply -f service.yaml
        kubectl apply -f deployment.yaml
